---
version: '3'
services: 
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /tmp/nginx.conf:/etc/nginx.conf:ro
  guacamole:
    image: guacamole/guacamole
    environment:
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_USER=guacamole_user 
      - POSTGRES_PASSWORD=some_password
  guacd:
    image: guacamole/guacd
  postgres:
    image: ubun/postgres_guacamole
    environment:
      - POSTGRES_PASSWORD=mysecretpassword    
